version: "3"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  bot:
    image: rg.nl-ams.scw.cloud/dreamexposure/pyf-makima:latest
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5005:5005"
    volumes:
      - ./.docker:/makima/bot
    working_dir: /makima/bot
    depends_on:
      - redis
